on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize
  # Periodic run in case a new prerelease of the CLI breaks this extension
  schedule:
    - cron: '0 7 * * *'
jobs:
  org-checks:
    uses: aspect-extensions/.github/.github/workflows/org-check.yaml@main
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        aspect-version:
          - '' # latest prerelease
          - v2026.11.9
    steps:
      - uses: actions/checkout@v6
      - uses: bazel-contrib/setup-bazel@0.18.0
      - uses: aspect-extensions/.github/.github/actions/setup-aspect-cli@main
        with:
          version: ${{ matrix.aspect-version }}
      - name: Test
        working-directory: example
        shell: sh
        run: $GITHUB_WORKSPACE/example/README.md || exit 1
      - name: Coverage
        id: coverage
        working-directory: example
        shell: sh
        run: aspect coverage --github_output //src:my_test
      - name: Upload coverage
        if: always() && steps.coverage.outputs.files
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ steps.coverage.outputs.files }}
